---
title: "Animal Model Comparison"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Description 

## References

1) [Animal Model usng MCMCglmm V1](https://drive.google.com/file/d/1AcxFs_sYGWh2JGXwdM-hMAU0HtQ18tbq/view?usp=sharing)  
2) [Animal Model usng MCMCglmm V2](https://onunicornsandgenes.blog/tag/mcmcglmm/)  
3) [Animal Model using BRMS](https://onunicornsandgenes.blog/tag/brms/)  

## Libraries 
```{r eval=F}
library(AlphaSimR)
library(AGHmatrix)
library(MCMCglmm)
library(brms)
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

# Simulated Population 

```{r eval=F}
## Founder population
FOUNDERPOP <- runMacs(nInd = 100,
                      nChr = 20,
                      inbred = FALSE,
                      species = "GENERIC")

## Simulation parameters 
SIMPARAM <- SimParam$new(FOUNDERPOP)
SIMPARAM$addTraitA(nQtlPerChr = 100,
                   mean = 100,
                   var = 10)
SIMPARAM$setGender("yes_sys")
SIMPARAM$setVarE(h2 = 0.3)

## Random mating for 9 more generations
generations <- vector(mode = "list", length = 10) 
generations[[1]] <- newPop(FOUNDERPOP,
                           simParam = SIMPARAM)

for (gen in 2:10) {
  
  generations[[gen]] <- randCross(generations[[gen - 1]],
                                  nCrosses = 10,
                                  nProgeny = 10,
                                  simParam = SIMPARAM)
  
}

## Put them all together
combined <- Reduce(c, generations)

## Extract phentoypes
pheno <- data.frame(animal = combined@id,
                    pheno = combined@pheno[,1])

# Important to scale phenotype otherwise priors could be incorrect
pheno$scaled_pheno <- as.vector(scale(pheno$pheno))

## Extract pedigree
ped <- data.frame(id = combined@id,
                  dam = combined@mother,
                  sire =combined@father)
ped2 <- ped
ped2$dam[ped$dam == 0] <- NA
ped2$sire[ped$sire == 0] <- NA
```

## MCMCglmm  
```{r eval=F}
## Gamma priors for variances
prior_gamma <- list(R = list(V = 1, nu = 1),
                    G = list(G1 = list(V = 1, nu = 1)))

## Fit the model
model_mcmc  <- MCMCglmm(scaled_pheno ~ 1,
                        random = ~ animal,
                        family = "gaussian",
                        prior = prior_gamma,
                        pedigree = ped2,
                        data = pheno,
                        nitt = 100000,
                        burnin = 10000,
                        thin = 10)

## Calculate heritability for heritability from variance components
h2_mcmc_object  <- model_mcmc$VCV[, "animal"] /
  (model_mcmc$VCV[, "animal"] + model_mcmc$VCV[, "units"])

## Summarise results from that posterior
h2_mcmc  <- data.frame(mean = mean(h2_mcmc_object),
                       lower = quantile(h2_mcmc_object, 0.025),
                       upper = quantile(h2_mcmc_object, 0.975),
                       method = "MCMC",
                       stringsAsFactors = FALSE)
```

## BRMS  
```{r eval=F}


# ped matrix needs to have 0s for missing values NOT NAs
ped[is.na(ped)] <-  0
A  <- Amatrix(ped)
  
  # Run model
model_brms2 <- brm(GrowthScale ~ ParentTrt + JarTrt + (1|gr(animal,cov=A)) + (1|damID) + (1|JarID),
                    data = pheno,
                    family = gaussian(),
                    data2 = list(A = A),
                    chains = 1,
                    cores = 4,
                    iter = 1000)

# Examine posterior distribution
posterior_brms <- posterior_samples(model_brms,
                                    pars = c("sd_animal", "sigma"))

# Calculate heritability for each sample
h2_brms  <- posterior_brms[,1]^2 /
  (posterior_brms[,1]^2 + posterior_brms[,2]^2)

# Mean heritability for all samples
    <- data.frame(mean = mean(h2_brms),
                       lower = quantile(h2_brms, 0.025),
                       upper = quantile(h2_brms, 0.975),
                       method = "BRMS",
                       stringsAsFactors = FALSE,
                       row.names=NULL)
```

