---
title: "Hypothetical Development Methylation Figures"
author: "adowneywall"
date: "11/27/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(cowplot)
```


```{r}
eggs <- data.frame(ls="eggs",m=rnorm(15,0.15,0.25))
sperm <- data.frame(ls="sperm",m=rnorm(15,0.9,0.015))
blastula <- data.frame(ls="blastula",m=rnorm(15,0.9,0.1))
larvae <- data.frame(ls="larvae",m=rnorm(15,0.85,0.15))
dat <- rbind(eggs,sperm,blastula,larvae)
dat$m[dat$m > 1] = 1
dat$m[dat$m < 0] = 0
dat$ls <- as.factor(dat$ls)

ggplot(dat,aes(x=ls,y=m)) + geom_boxplot() + ylim(0,1) +
  theme_cowplot() + labs(x="Life Stages",y="DNA Methylation")


```


```{r}
library(MASS)


mu=c(rnorm(230,0.2,0.02),rnorm(800,0.73,0.11))
mu[mu < 0] = 0
mu[mu > 1] = 1
hist(mu)
# base methylation
devV <- 0.01
selV <- 0.01
N <- length(mu)
# Covariance 0.5
covV <- 0.1
sigma <- matrix(c(devV,devV*covV,selV*covV,selV),ncol=2)
out <- mvrnorm(N,c(0,0),sigma)
parent <- out[,1]+mu
parent[parent < 0] = 0
parent[parent > 1] = 1
offspring <- out[,2]+mu
offspring[offspring < 0] = 0
offspring[offspring > 1] = 1
plot(parent~offspring,xlab="Mid point Parental Methylation",ylab="Offspring Methylation",main="Transmission = 0.5")
abline(a=0,b=1)
  # Covariance 0.8
covV <- 0.8
sigma <- matrix(c(devV,devV*covV,selV*covV,selV),ncol=2)
out <- mvrnorm(N,mu,sigma)
plot(out[,1]~out[,2],xlab="Development Environment",ylab="Selection Environment",main="Predictability = 0.8")
abline(a=0,b=1)
# Covariance 0.99
covV <- 0.99
sigma <- matrix(c(devV,devV*covV,selV*covV,selV),ncol=2)
out <- mvrnorm(N,mu,sigma)
plot(out[,1]~out[,2],xlab="Development Environment",ylab="Selection Environment",main="Predictability = 0.99")
abline(a=0,b=1)
```


